import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, Summary } from "@/components/SiteChrome";
import { mailto, site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `How ${site.game} handles your data, in plain words.`,
};

/**
 * Written against what the game actually does rather than from a template.
 *
 * Every row in the table below corresponds to something real in the client or the backend —
 * an anonymous Firebase account, a Firestore save document, a published grove card, a
 * store receipt, a mediation SDK. A policy that lists data an app does not collect is as
 * wrong as one that omits data it does, and it is the kind of wrong a regulator reads as
 * carelessness rather than caution.
 */
export default function Privacy() {
  return (
    <LegalPage
      title="Privacy Policy"
      intro={`This explains what ${site.game} collects, why, and what you can do about it.`}
    >
      <Summary>
        <p className="mb-2">
          You can play the whole game without giving us your name, your email address or
          anything else about you. An anonymous account is created so your progress can be
          saved and restored — it identifies a save file, not a person.
        </p>
        <p className="mb-2">
          We show adverts, and those are provided by third parties who may use an
          advertising identifier. In the EU and the UK you are asked first, and you can
          change your answer at any time from the settings screen.
        </p>
        <p>
          We do not sell your data. We have no interest in who you are — only in whether the
          game works.
        </p>
      </Summary>

      <h2 id="who-we-are">Who we are</h2>
      <p>
        {site.game} is published by {site.entity}, {site.address}. For the purposes of the UK
        and EU General Data Protection Regulation, we are the data controller for the
        information described here. You can reach us at{" "}
        <a href={`mailto:${site.email}`}>{site.email}</a>.
      </p>

      <h2 id="what-we-collect">What we collect, and why</h2>
      <p>
        We have tried to make this specific rather than exhaustive-sounding. If something is
        not in this table, the game does not collect it.
      </p>

      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th>What</th>
              <th>Why</th>
              <th>When</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <strong>An anonymous account identifier</strong>, generated by Firebase
                Authentication
              </td>
              <td>
                So your progress can be saved to our servers and restored on a new device.
                It is a random string. It is not linked to your name, email or phone number
                unless you choose to link a sign-in account.
              </td>
              <td>First launch</td>
            </tr>
            <tr>
              <td>
                <strong>Your game progress</strong> — which glades you have finished, your
                best moves and times, hearts, streak, in-game currency ledgers, the grove you
                have built, and your settings
              </td>
              <td>
                So the game can continue where you left off, and so the same progress appears
                on your other devices.
              </td>
              <td>As you play</td>
            </tr>
            <tr>
              <td>
                <strong>A public grove card</strong> — the keeper name you chose, your grove
                score, and where things stand in your grove
              </td>
              <td>
                So other players can see your grove on the boards. This is the only
                information other players can see, and you can switch it off in the settings
                screen at any time, which removes your card.
              </td>
              <td>Only if the boards are enabled</td>
            </tr>
            <tr>
              <td>
                <strong>Your chosen keeper name</strong>, held as a reservation so two players
                cannot claim the same one
              </td>
              <td>
                To keep names unique. You choose this name; please do not use your real name
                if you would rather it were not public.
              </td>
              <td>If you set a name</td>
            </tr>
            <tr>
              <td>
                <strong>A linked sign-in</strong> — an identifier from Apple or Google, and
                whatever that provider passes to us
              </td>
              <td>
                Only if you choose to link an account so your progress survives losing your
                device. We do not receive your password.
              </td>
              <td>Only if you link</td>
            </tr>
            <tr>
              <td>
                <strong>Purchase records</strong> — the store transaction identifier and what
                was bought
              </td>
              <td>
                To confirm a purchase with Apple or Google and to give you what you paid for,
                once. <strong>We never see your card details</strong> — the payment happens
                inside the store, not inside the game.
              </td>
              <td>If you buy something</td>
            </tr>
            <tr>
              <td>
                <strong>Advertising identifiers and related data</strong>, handled by our
                advertising partners
              </td>
              <td>
                To show adverts and to pay for the game being free. See{" "}
                <a href="#advertising">Advertising</a> below.
              </td>
              <td>When adverts are shown</td>
            </tr>
            <tr>
              <td>
                <strong>Basic technical information</strong> — device model, operating system
                version, language, and error diagnostics
              </td>
              <td>
                To find out why something crashed or a screen drew wrongly on a device we do
                not own.
              </td>
              <td>As needed</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h3>What we deliberately do not collect</h3>
      <ul>
        <li>Your name, unless you type one in as your keeper name.</li>
        <li>Your email address, unless you email us or link a sign-in account.</li>
        <li>Your contacts, photos, microphone, camera or precise location.</li>
        <li>Your payment card details. Those never reach us.</li>
      </ul>

      <h2 id="legal-bases">Our legal bases (UK and EU)</h2>
      <ul>
        <li>
          <strong>Performance of a contract</strong> — saving and restoring your progress,
          and honouring a purchase. Without these the game does not work.
        </li>
        <li>
          <strong>Consent</strong> — personalised advertising, and appearing on the public
          boards. Both are optional and both can be withdrawn.
        </li>
        <li>
          <strong>Legitimate interests</strong> — keeping the game working, diagnosing
          crashes, and preventing fraud and abuse of the in-game economy.
        </li>
        <li>
          <strong>Legal obligation</strong> — keeping records of purchases for tax and
          accounting.
        </li>
      </ul>

      <h2 id="advertising">Advertising</h2>
      <p>
        The game is free, and adverts are how it is paid for. Adverts are optional in the
        sense that matters: there are no forced adverts between levels. Every advert in{" "}
        {site.game} is one you choose to watch in exchange for something.
      </p>
      <p>
        Adverts are delivered by <strong>Unity LevelPlay</strong> (ironSource) as the
        mediation platform, and by the advertising networks it works with, which currently
        include <strong>Unity Ads</strong> and <strong>Google AdMob</strong>. These partners
        are independent controllers of the data they collect and have their own policies:
      </p>
      <ul>
        <li>
          <a href="https://unity.com/legal/game-player-and-app-user-privacy-policy" rel="noopener noreferrer" target="_blank">
            Unity — player and app user privacy policy
          </a>
        </li>
        <li>
          <a href="https://policies.google.com/technologies/partner-sites" rel="noopener noreferrer" target="_blank">
            Google — how Google uses information from sites or apps that use our services
          </a>
        </li>
      </ul>

      <h3>Your choice, and how to change it</h3>
      <p>
        If you are in the European Economic Area or the United Kingdom, you are asked before
        any personalised advertising happens, through a Google-certified consent form. If you
        decline, you will still see adverts and still receive the rewards for watching them —
        they will simply not be based on a profile of you.
      </p>
      <p>
        You can change your answer at any time: open <strong>Settings</strong> in the game and
        choose <strong>Privacy &amp; ad choices</strong>.
      </p>
      <p>
        On iOS, you are separately asked whether the app may use the device advertising
        identifier. That answer belongs to the operating system and can be changed in{" "}
        <strong>iOS Settings › Privacy &amp; Security › Tracking</strong>.
      </p>

      <h2 id="sharing">Who your data is shared with</h2>
      <p>We use a small number of providers, each for one job:</p>
      <ul>
        <li>
          <strong>Google Firebase</strong> (Authentication, Cloud Firestore, Cloud Functions)
          — the anonymous account and the saved progress. Data is stored in the European
          Union.
        </li>
        <li>
          <strong>Apple and Google</strong> — app distribution, payments and purchase
          verification.
        </li>
        <li>
          <strong>Unity LevelPlay and its advertising networks</strong> — advertising, as
          described above.
        </li>
      </ul>
      <p>
        We do not sell personal information, and we do not share it for cross-context
        behavioural advertising beyond what the advertising partners above do with your
        consent.
      </p>

      <h2 id="transfers">International transfers</h2>
      <p>
        Our save data is held in the European Union. Some of our providers are based in the
        United States and may process data there, relying on the European Commission&rsquo;s
        standard contractual clauses or an equivalent safeguard.
      </p>

      <h2 id="retention">How long we keep it</h2>
      <ul>
        <li>
          <strong>Saved progress</strong> — for as long as the account is in use, and for up
          to 24 months after it goes quiet, after which it may be deleted.
        </li>
        <li>
          <strong>Your public grove card</strong> — until you switch the boards off or delete
          your data, whichever comes first.
        </li>
        <li>
          <strong>Purchase records</strong> — for as long as tax and accounting law requires,
          which is generally seven years. These survive deletion of your game data, because
          we are not permitted to destroy them.
        </li>
      </ul>

      <h2 id="rights">Your rights</h2>
      <p>
        If the UK or EU GDPR applies to you, you have the right to ask for a copy of your
        data, to have it corrected, to have it deleted, to restrict or object to how we use
        it, and to withdraw consent you have given. Similar rights exist under the California
        Consumer Privacy Act and other laws.
      </p>
      <p>
        The quickest routes are in the game itself — the boards opt-out is in Settings, and
        so is the advertising choice. For anything else, or to delete everything, see{" "}
        <Link href="/delete-account">deleting your data</Link> or write to{" "}
        <a href={mailto("Privacy request")}>{site.email}</a>. We answer within 30 days.
      </p>
      <p>
        Because accounts are anonymous by default, we may need you to prove which account is
        yours before we act on a request — usually by sending the request from a linked
        sign-in address, or by giving us the account identifier shown in the game.
      </p>
      <p>
        If you think we have handled your data badly, you can complain to your national data
        protection authority.
      </p>

      <h2 id="children">Children</h2>
      <p>
        {site.game} is a general-audience game. It is not directed at children under 13, and
        it is not registered as a child-directed app with our advertising partners. We do not
        knowingly collect personal information from children under 13. If you believe a child
        has given us information, write to{" "}
        <a href={mailto("Child privacy")}>{site.email}</a> and we will delete it.
      </p>

      <h2 id="this-website">This website</h2>
      <p>
        This site is static. It sets no cookies, runs no analytics, and does not track you.
        The only thing it knows about you is what your browser tells our host in order to
        send you the page.
      </p>

      <h2 id="changes">Changes</h2>
      <p>
        If we change this policy we will update the date at the top, and for anything
        significant we will say so in the game before the change takes effect.
      </p>

      <h2 id="contact">Contact</h2>
      <p>
        {site.entity}
        <br />
        {site.address}
        <br />
        <a href={`mailto:${site.email}`}>{site.email}</a>
      </p>
    </LegalPage>
  );
}
